# Generated by Django 6.0.7 on 2026-07-26 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_accepting_orders'),
        ('vendor', '0002_alter_fooditem_options_fooditem_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(default='START', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=10)),
                ('last_message_id', models.IntegerField(blank=True, null=True)),
                ('last_bot_message_id', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('current_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.foodcategory')),
                ('current_restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
