# Generated by Django 6.0.7 on 2026-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordering_platform',
            field=models.CharField(choices=[('WEB', 'Web'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp')], default='WEB', max_length=20),
        ),
    ]
