# Generated by Django 6.0.7 on 2026-07-23 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_prebooking_payment_status'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prebooking',
            name='picked_up_by_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='pickup_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='pickup_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='qr_status',
            field=models.CharField(choices=[('NOT_GENERATED', 'Not Generated'), ('ACTIVE', 'Active'), ('SCANNING', 'Scanning'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='NOT_GENERATED', max_length=20),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PickupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('verification_type', models.CharField(choices=[('QR', 'QR Code'), ('MANUAL', 'Manual Entry')], max_length=20)),
                ('verification_source', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate')], max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_logs', to='orders.prebooking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_logs', to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
